### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by orloffm** [isc30/xlnt-wasm#2]
Ivan, so the project with the _possibility to export pivot tables to excel_ ;) now encountered that this implementation doesn't support non-ASCII characters. 

For example, this fails:
````
sheet.using_cell("A1", c => c.set_value('ą'));
````

I suspect (see https://github.com/emscripten-core/emscripten/issues/7174#issuecomment-437761839) that the binary should be recompiled with `-s EMBIND_STD_STRING_IS_UTF8=1`. From your experience, will that help? And may I ask you to recompile the .wasm file?

Thanks.

Mikhail

**Comment by isc30** [comment]
Hi, I just compiled a version with UTF8 and seems like it's working well, I'll push the code and NPM package as soon as I can.
Thanks for the observation :)

**Comment by isc30** [comment]
done, please let me know if this change fixes your issues in *that project that exports pivot tables to excel*

**Comment by orloffm** [comment]
Yes, all good now, thanks!
